name: /Users/camilledevalk/repositories/yquantum-hartford-capgemini/.conda
channels:
  - conda-forge
dependencies:
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311heffc1b2_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hb547adb_1
  - brotli-bin=1.1.0=hb547adb_1
  - brotli-python=1.1.0=py311ha891d26_1
  - bzip2=1.0.8=h93a5062_5
  - ca-certificates=2024.2.2=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py311h4a08483_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311hd03642b_0
  - cryptography=42.0.5=py311h71175c2_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py311h92babd0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.8=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fonttools=4.50.0=py311h05b510d_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=hadb7bae_2
  - gf2x=1.3.0=hdaa854c_2
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.3.0=hebf3989_1
  - gmpy2=2.1.2=py311h2ba9262_1
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.0=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - ibm-cloud-sdk-core=3.19.2=pyhd8ed1ab_0
  - ibm-platform-services=0.53.2=pyhd8ed1ab_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyh3cd1d5f_0
  - ipython=8.22.2=pyh707e725_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - json5=0.9.24=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h267d04e_3
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.21.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.4=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.6=pyh5bfe37b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311h267d04e_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.13.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.1.5=pyhd8ed1ab_0
  - jupyterlab-git=0.50.0=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.25.4=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py311he4fd1f5_1
  - lcms2=2.16=ha0e7c42_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=21_osxarm64_openblas
  - libbrotlicommon=1.1.0=hb547adb_1
  - libbrotlidec=1.1.0=hb547adb_1
  - libbrotlienc=1.1.0=hb547adb_1
  - libcblas=3.9.0=21_osxarm64_openblas
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.20=h93a5062_0
  - libexpat=2.6.2=hebf3989_0
  - libffi=3.4.2=h3422bc3_5
  - libflint=2.9.0=h173eafc_ntl_100
  - libgfortran=5.0.0=13_2_0_hd922786_3
  - libgfortran5=13.2.0=hf226fd6_3
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=21_osxarm64_openblas
  - libopenblas=0.3.26=openmp_h6c19121_0
  - libpng=1.6.43=h091b4b1_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.45.2=h091b4b1_0
  - libtiff=4.6.0=h07db509_3
  - libwebp-base=1.3.2=hb547adb_0
  - libxcb=1.15=hf346824_0
  - libzlib=1.2.13=h53f4e23_5
  - llvm-openmp=18.1.2=hcd81f8e_0
  - markupsafe=2.1.5=py311h05b510d_0
  - matplotlib=3.8.3=py311ha1ab1f8_0
  - matplotlib-base=3.8.3=py311hb58f1d1_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - mpc=1.3.1=h91ba8db_0
  - mpfr=4.2.1=h9546428_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.3=pyhd8ed1ab_0
  - nbdime=4.0.1=pyhd8ed1ab_0
  - nbformat=5.10.3=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h078ce10_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - ntl=11.4.3=hbb3f309_1
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.2=h9f1df11_0
  - openssl=3.2.1=h0d3ecfb_1
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.1=py311hfbe21a1_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pbr=6.0.0=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py311hb9c5795_0
  - pip=24.0=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311h05b510d_0
  - pthread-stubs=0.4=h27ca646_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.6.4=pyhd8ed1ab_0
  - pydantic-core=2.16.3=py311h94f323b_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pylatexenc=2.10=pyhd8ed1ab_0
  - pyobjc-core=10.2=py311h665608e_0
  - pyobjc-framework-cocoa=10.2=py311h665608e_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pyspnego=0.9.1=py311heffc1b2_2
  - python=3.11.8=hdf0ec26_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-symengine=0.11.0=py311h2031a10_1
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py311heffc1b2_1
  - pyzmq=25.1.2=py311h6727e71_0
  - qiskit=1.0.2=py311h94f323b_0
  - qiskit-ibm-runtime=0.22.0=pyhd8ed1ab_0
  - readline=8.2=h92ec313_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests_ntlm=1.2.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.18.0=py311ha958965_0
  - ruamel.yaml=0.18.6=py311h05b510d_0
  - ruamel.yaml.clib=0.2.8=py311h05b510d_0
  - rustworkx=0.14.2=py311hcd5b669_0
  - scipy=1.12.0=py311h4f9446f_2
  - send2trash=1.8.2=pyhd1c38e8_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stevedore=5.2.0=pyhd8ed1ab_0
  - symengine=0.11.2=h417e0f7_1
  - sympy=1.12=pypyh9d50eac_103
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py311h05b510d_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hb547adb_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hebf3989_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=h4f39d0f_0
  - pip:
      - antlr4-python3-runtime==4.13.1
      - appdirs==1.4.4
      - docplex==2.27.239
      - fastdtw==0.3.4
      - frozendict==2.4.1
      - html5lib==1.1
      - inflection==0.5.1
      - lxml==5.2.1
      - more-itertools==10.2.0
      - multitasking==0.0.11
      - nasdaq-data-link==1.0.4
      - networkx==3.2.1
      - openqasm3==0.5.0
      - peewee==3.17.1
      - ply==3.11
      - qbraid==0.5.3
      - qiskit-aer==0.14.0.1
      - qiskit-algorithms==0.3.0
      - qiskit-finance==0.4.1
      - qiskit-optimization==0.6.1
      - yfinance==0.2.37
prefix: /Users/camilledevalk/repositories/yquantum-hartford-capgemini/.conda
